name: Docker Compose

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Docker and Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker.io
          sudo apt-get install docker-compose
      - name: Build and run docker-compose
        run: |
          sudo docker-compose up -d
